### PR TITLE
Return heatmaps as png file to the user

### PR DESCRIPTION
**Pull request by itsfrank98**
Added opencv to the requirements
Now the api returns a PNG image of the CT scan's heatmap

### CODE REVIEW

**Review by peppocola — APPROVED** [review]

**Comment by loreloc** [comment]
Previous commits on main related to issue #18 are deleted in this branch.
The main branch shall be merged on api_2 before closing this PR.

**Review by peppocola — APPROVED** [review]

**Review by peppocola — CHANGES_REQUESTED** [review]
some lines have been removed as @loreloc pointed out, @itsfrank98 check please

**Comment by loreloc** [comment]
It seems all is ok now. I would suggest choosing "Squash and merge" this pull request.

**Review by peppocola — APPROVED** [review]
nice, let's squash 🌊

**Pull request merged**
