### PR TITLE
Grafana

### PR DESCRIPTION
**Pull request by itsfrank98**
Added script files for running grafana and prometheus in linux. Fixed the prometheus yml file, which now can be the same for linux and windows users

### CODE REVIEW

**Review by peppocola — APPROVED** [review]
all working! great job :D
image

**Review by loreloc — APPROVED** [review]
Based !

**Comment by DanielaGrassi** [comment]
Amazing like Spiderman

**Review by DanielaGrassi — APPROVED** [review]
Very nice

**Comment by itsfrank98** [comment]
closes #40

**Comment by itsfrank98** [comment]
closes #40

**Pull request merged**
