### PR TITLE
Files for making prometheus compliant with alertmanager

### PR DESCRIPTION
**Pull request by itsfrank98**
In this PR I edited the prometheus configuration file and also added new files for adding a rule that fires an alert when the service is down for more than one minute. The rule is contained in `alert_rules.yml`.

- `prometheus.yml` was edited by adding the alerting section
- `alertmanager.yml` is the configuration for AlertManager. It is configured for sending me an email when an alert is fired
- I added a `docker_compose.yml` file. It creates two containers, one for Prometheus and another one for AlertManager, mounting the required configuration files, and runs them together. Docker compose, in fact, is the tool devoted to running multiple containers together and we could use it for also running the Grafana container in order to avoid manually launching three containers each time. To run the file, type `docker-compose up` (it will ask you to download docker-compose if you don't have it)

### CODE REVIEW

**Review by peppocola — APPROVED** [review]
nice job 🚀

**Comment by peppocola** [comment]
The script should be in the `scripts` folder

**Comment by peppocola** [comment]
Also insert a script to run `node_exporter`

**Comment by itsfrank98** [comment]
closes #58

**Comment by loreloc** [comment]
Alerting is working correctly!

1. The ```run-locust.sh``` bash script (without ```cd ..```) can be run in the root directory of the project
2. We can use ```./``` instead of ```$PWD``` (optional, not very important)

**Review by loreloc — APPROVED** [review]
Good!

**Pull request merged**
